---
title: "Common Loon Data Tidying"
author: "Ellie Gabrielson, Will Draxler, Autumn Pauly"
output: pdf_document
---


# Loading the Packages and Data
```{r loading-packages}
library(tidyverse)
library(lubridate)
```

# Loading Data - 2023
```{r loading-data}
#2023
all_bird_untidy_2023 <- read_csv("loons_2023.csv")
loons_2023 <- read_csv("loons_2023.csv")

#2024
loons_2024 <- read_csv("loons_2024.csv")
```

# Tidying the Data
## Exposure
```{r refactor-exposure-level}
#assigning exposure level to locations
loons_2023 <- loons_2023 %>% 
  mutate(shelter_gradient = case_when(location == "BAR HARBOR PIER" ~ "exposed",
                                      location == "SEAL HARBOR BEACH" ~ "moderate",
                                      location == "BRACY HARBOR" ~ "moderate",
                                      location == "NORTHEAST HARBOR" ~ "moderately_sheltered",
                                      location == "SOMES SOUND" ~ "sheltered",
                                      location == "SOUTHWEST HARBOR" ~ "moderately_sheltered",
                                      location == "SEAWALL" ~ "exposed",
                                      location == "SEAL COVE" ~ "moderately_exposed",
                                      location == "SAND BEACH" ~ "moderately_exposed"))
 
#releveling the exposure levels from most exposed to least exposed 
shelter_factor <- fct_relevel(loons_2023$shelter_gradient, c(
                "exposed", 
                "moderately_exposed",
                "moderate",
                "moderately_sheltered",
                "sheltered"))

#saving a dataset to include only loons and the shelter factor
loons_2023 <- loons_2023 %>% 
  mutate(shelter_factor = shelter_factor) %>% 
  filter(species == "COMMON LOON")

#counting how many different exposure observations we have
loons_2023 %>% 
  count(shelter_factor)
```

## Changing `chr` variables to `num`

There are a number of variables within this dataset that are character variables that should be numeric variables (i.e. meters_offshore, longitude, latitude)

```{r chr-to-num}

#Change character numbers to numeric
loons_2023 <- loons_2023 %>% 
  mutate(meters_offshore = as.numeric(meters_offshore)) %>% 
  mutate(latitude = as.numeric(latitude)) %>% 
  mutate(longitude = as.numeric(longitude)) %>% 
  mutate(barometer = as.numeric(barometer)) %>% 
  mutate(date = as_date(date, format = "%m/%d/%Y")) %>% 
  mutate(time = hms::as_hms(time)) %>% 
  select(-year, -day, -month)

glimpse(loons_2023)
```


## Location
```{r location-tidying}

#determining how many locations we have
unique(loons_2023$location)

```

## Behavior
```{r behavior-tidying}

unique(loons_2023$behavior)

#Count occurence of behaviors
loons_2023_behavior <- loons_2023 %>% 
  filter(species == "COMMON LOON") %>% 
  group_by(date, behavior, species, tide, tide_percentage) %>% 
  count(behavior)

loons_2023_behavior

#Count the occurrences of behavior of loons
ggplot(data = loons_2023_behavior, mapping = aes(x = behavior)) + 
  geom_bar()

#Count how many low, high, and mid tide observations we have
ggplot(data = loons_2023_behavior, mapping = aes(x = tide)) + 
  geom_bar()

```
