---
title: "Common Loon 2024 Data Tidying"
subtitle: "for Statistics Final Project"
author: "Draxler and Pauly"
output: 
  html_document: 
    toc: true
---
## Loading the Packages and Data

We will be using the `tidyverse` and `lubridate` packages to assist with data tidying. 

```{r loading-packages, warning=FALSE, message=FALSE}
library(tidyverse)
library(lubridate)
```

## Loading Data
```{r}
loons_2024 <- read_csv("loons_2024.csv")
```

### Filtering for Loons
```{r only-loons-2024}
loons_2024 <- loons_2024 %>% 
  filter(species == "common_loon")
```

### Tide
The six tidal stages should be releveled to be reflective of the tidal cycle. 

```{r refactor-tide-2024, message=FALSE, warning=FALSE}
#releveling the exposure levels from most exposed to least exposed 
loons_2024 <- loons_2024 %>% 
  mutate(tide = fct_relevel(loons_2024$tide, c(
                "high_ebb", 
                "mid_ebb",
                "low_slack",
                "low_flood", 
                "mid_flood",
                "high_flood", 
                "high_slack")))
```


```{r}
loons_dive_2024 <- loons_2024 %>% 
  filter(species == "common_loon") %>% 
  select(tide, behavior, dive_time_obs, tidal_height, latitude, longitude, meters_offshore, location) %>% 
  filter(dive_time_obs != "n/a") %>% 
  filter(dive_time_obs != "na")

loons_dive_2024 <- loons_dive_2024 %>% 
  separate_longer_delim(dive_time_obs, delim = ",")

loons_dive_2024 <- loons_dive_2024 %>% 
  separate_wider_delim(latitude, delim = ",", names = c("latitude", "longitude2"), too_few = "align_start") %>% 
  mutate(longitude2 = as.numeric(longitude2)) %>% 
  mutate(latitude = as.numeric(latitude))

loons_dive_2024 <- loons_dive_2024 %>%
  mutate(dive_time_obs = as.numeric(dive_time_obs))

loons_dive_2024 <- loons_dive_2024 %>% 
  mutate(general_tide = fct_recode(tide, "low" = "low_flood", 
                           "low" = "low_slack",
                           "mid" = "mid_flood",
                           "mid" = "mid_ebb",
                           "high" = "high_flood",
                           "high" = "high_slack",
                           "high" = "high_ebb"))

loons_dive_2024_1 <- loons_dive_2024 %>% 
  filter(is.na(longitude2) == F ) %>% 
  mutate(longitude = longitude2) %>% 
  select(-longitude2)

loons_dive_2024_2 <- loons_dive_2024 %>% 
  filter(is.na(longitude) == F ) %>% 
  select(- longitude2)

loons_dive_2024 <- loons_dive_2024_1 %>% 
  bind_rows(loons_dive_2024_2)

loons_dive_2024 %>% 
  write_csv("loons_dive_2024.csv")
```




















